---
name: sample-python-flask-app

instance_groups:
- name: webapp
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sample-python-flask-app
    release: sample-python-flask-app
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: sample-python-flask-app
  version: 1.0.0
  url:  https://github.com/cloudfoundry-community/sample-python-flask-app-boshrelease/releases/download/v1.0.0/sample-python-flask-app-1.0.0.tgz
  sha1: 9c1854ba220c66e4bd7658012c4aef53637c291e
